version: "3.8"
services:
    api:
        build:
            context: ./api
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"