version: "3.8"
services:
    api:
        build:
            context: ./api
        restart: unless-stopped
        ports:
            - "5000:5000"
        image: lordronz/b201_baktilab:api
        volumes:
            - ./api/.env:/code/.env
    nginx:
        restart: unless-stopped
        image: nginx:1.18.0-alpine
        ports:
            - "443:443"
        image: lordronz/b201_baktilab:nginx
        volumes:
            - ./nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
            - ./nginx/ssl/key.pem:/etc/nginx/ssl/key.pem
            - ./nginx/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf