version: "3.8"
services:
    api:
        build:
            context: ./api
        ports:
            - "5000:5000"
        image: lordronz/b201_baktilab:api
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "443:443"
        image: lordronz/b201_baktilab:nginx